// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgDcBBzXdGzELcWq2ARufQRt2oMb_3XRk',
    appId: '1:602422928885:web:07b337647c451933b8ecbc',
    messagingSenderId: '602422928885',
    projectId: 'chatapp-8496f',
    authDomain: 'chatapp-8496f.firebaseapp.com',
    storageBucket: 'chatapp-8496f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFSKlHRGar68o9KIaum5qn9giFUOTY-8A',
    appId: '1:602422928885:android:6be6c364b2be20e1b8ecbc',
    messagingSenderId: '602422928885',
    projectId: 'chatapp-8496f',
    storageBucket: 'chatapp-8496f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC--Bw1KlIXxh4XsW7mFLKx1eA0sxL_x2E',
    appId: '1:602422928885:ios:e9ae05b678d26cf7b8ecbc',
    messagingSenderId: '602422928885',
    projectId: 'chatapp-8496f',
    storageBucket: 'chatapp-8496f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC--Bw1KlIXxh4XsW7mFLKx1eA0sxL_x2E',
    appId: '1:602422928885:ios:e9ae05b678d26cf7b8ecbc',
    messagingSenderId: '602422928885',
    projectId: 'chatapp-8496f',
    storageBucket: 'chatapp-8496f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgDcBBzXdGzELcWq2ARufQRt2oMb_3XRk',
    appId: '1:602422928885:web:a6c88e375ee1378ab8ecbc',
    messagingSenderId: '602422928885',
    projectId: 'chatapp-8496f',
    authDomain: 'chatapp-8496f.firebaseapp.com',
    storageBucket: 'chatapp-8496f.firebasestorage.app',
  );
}
